name: "Checks"
on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  type-check:
    name: "Type Check"
    runs-on: ubuntu-22.04
    permissions:
      contents: read # This is required to checkout the repo
    steps:
      - uses: pnpm/action-setup@v2
        with:
          run_install: true
      - run: pnpx type-check
  lint:
    name: "Lint"
    runs-on: ubuntu-22.04
    permissions:
      contents: read # This is required to checkout the repo
    env:
      NODE_OPTIONS: "--max_old_space_size=4096"
    steps:
      - uses: pnpm/action-setup@v2
        with:
          run_install: true
      - run: pnpx lint
